### ISSUE TITLE
"Get History" messages does not include usernames and timestamps

### ISSUE THREAD

**Issue by alesandar** [dylex/slack-libpurple#46] opened 2018-03-22 11:23 UTC
Open up any of the Slack channels you're participating or simply start a new chat with another member of your team, click on the **Conversation** menu button, then click **More > Get History**, type some integer and click **Get**. The plugin fetches older messages successfully, but they seem to lack at least usernames and timestamps. Every message starts on a new row, but there's no identifier who was the sender and when it was sent.

**Comment by dmick** [comment] 2018-03-23 20:45
Me Too.

**Comment by dmick** [comment] 2018-03-23 22:10
FWIW the debug window shows that the response includes user and timestamp, so it's an interpretation thing in the plugin.

**Comment by dmick** [comment] 2018-03-24 01:29
....or something. the plugin passes it on to Pidgin, but Pidgin isn't displaying it, for reasons I haven't parsed out yet.

**Comment by dmick** [comment] 2018-03-24 04:04
There doesn't seem to be any way to cause libpurple to avoid the log but also decorate the message with user and timestamp.  So for now I'm just removing PURPLE_MESSAGE_NO_LOG:

```
diff --git a/slack-message.c b/slack-message.c
index ead4c94..8a57d80 100644
--- a/slack-message.c
+++ b/slack-message.c
@@ -417,7 +417,6 @@ static void handle_message(SlackAccount *sa, SlackObject *obj, json_value *json,
                                        !strcmp(subtype, "group_topic"))
                                purple_conv_chat_set_topic(chat, user ? user->object.name : user_id, json_get_prop_strptr(json, "topic"));
                }
-               
                serv_got_chat_in(sa->gc, chan->cid, user ? user->object.name : user_id ?: username ?: "", flags, html->str, mt);
        } else if (SLACK_IS_USER(obj)) {
                SlackUser *im = (SlackUser*)obj;
@@ -502,7 +501,7 @@ static void get_history_cb(SlackAccount *sa, gpointer data, json_value *json, co
                if (g_strcmp0(json_get_prop_strptr(msg, "type"), "message"))
                        continue;
 
-               handle_message(sa, obj, msg, PURPLE_MESSAGE_RECV | PURPLE_MESSAGE_DELAYED | PURPLE_MESSAGE_NO_LOG);
+               handle_message(sa, obj, msg, PURPLE_MESSAGE_RECV | PURPLE_MESSAGE_DELAYED);
        }
        /* TODO: has_more? */
```

**Comment by dylex** [comment] 2018-03-24 17:19
Hm, I mainly use finch, which seems to handle `PURPLE_MESSAGE_NO_LOG` messages differently and does display names, so hadn't noticed this problem. I'll bring it up with the pidgin devs to figure out the intended behavior. I suppose there's no harm in logging duplicate messages if it comes to that.

**Comment by zoltan-dulac** [comment] 2018-04-20 18:00
Hey @dylex 

This has been bugging me for a while, and I just realized that @dmick outlined a fix for this above.  I put it in the `history-fix` branch.  Can we merge this into the build?  It is super helpful.

https://github.com/dylex/slack-libpurple/tree/history-fix

**Closed** 2018-04-24 13:32 UTC
