### ISSUE TITLE
URLs sent/received are not visible.

### ISSUE THREAD

**Issue by zoltan-dulac** [dylex/slack-libpurple#10] opened 2017-11-10 18:11 UTC
When I send a URL to a group/buddy, it is not visible (but the rest of the message is).  The same goes when someone sends me a URL.  Is this related to  https://github.com/dylex/slack-libpurple/issues/7 ?

**Comment by dylex** [comment] 2017-11-12 14:07
I was able to reproduce this for messages sent to chats, and have now fixed that. However, I can't make it happen for messages sent to IMs or received from either -- in both cases I can see the URLs (but not the attached auto-generated summary -- that is related to #7). If you can provide steps to reproduce, or even better a section of the debug log with the affected message, that'd be great.

**Comment by zoltan-dulac** [comment] 2017-11-13 18:38
I tried to replicate it for direct messages, and I couldn't.  I must have been mistaken.  If I find out that it does happen, I'll open another issue.  

Thanks so much for fixing this.  Is there a way you can show me how you fixed this with a diff or something? I tried fixing this myself and it worked in a really wonky way.  I'd like to learn the "right way" to fix it so I can see if I can contribute some code in the future.

**Comment by dylex** [comment] 2017-11-13 18:44
You can click on the commit above to see the patch. Basically I just wasn't calling the function to convert from slack's message format to libpurple's html format for the send acknowledge message for chats. libpurple is a bit assymetric this way, in that when you send to a chat, you can wait to write the message to the conversation until it's actually sent, while for IMs it writes it to the conversation for you as soon as you send. So, for IMs there's no reason to reformat, since it's already in libpurple format, but for chats I'm using the message send back from slack, not the original message.

(The work for #7 is a bit more involved, because you need to use other parts of the json message to construct the libpurple html somehow, but that mainly just needs someone to define a template of which fields should go where, if you want to look into that.)

**Comment by dylex** [comment] 2017-11-22 16:15
Closing for chat sent URL fix.

**Closed by dylex** 2017-11-22 16:15 UTC
