### ISSUE TITLE
Pidgin doesn't show message from new contacts

### ISSUE THREAD

**Issue by kurnevsky** [dylex/slack-libpurple#22] opened 2018-01-08 13:53 UTC
It seems that if somebody who wasn't in your contact list writes you a message you won't see it. I may be wrong because to reproduce this I need to find someone who hasn't written me yet. But I definitely had missed messages.

**Comment by kurnevsky** [comment] 2018-01-08 16:01
Just checked it - got only second message, first one was missed.

**Comment by dylex** [comment] 2018-01-10 15:51
I could see this happening if we're getting the `message` event before the `im_open`/`im_created` event, but I didn't think slack was supposed to do that. I'll try to reproduce this in order to get some debug logs, but if you happen to have them already that'd be great, too.

**Comment by dylex** [comment] 2018-02-22 01:09
I've been trying to reproduce this, but have so far been unable to. I think I need a larger slack to test with. On my small test slack, there are few enough users that everyone already shows up in the IM list by default.

**Comment by Itsmedenise** [comment] 2018-02-27 06:09
I have been able to construct at least one workflow where this can happen.
Starting Position:
- Slack Workspace with two users User1 that uses Pidgin and User2 that uses the Browser
- direct message channel between User1 and User2 is opened (im.open method)

Step 1: Open Pidgin and the Browser
Step 2: close (im.close method) the direct message channel between User1 and User2 from an application other than pidgin. Pidgin should recive a RTM with type "im_close"
Step 3: Send a Message from User2 (Browser) to User1 (Pidgin). Pidgin will still recive the message RTM but doesn't handle it. 

This example is more theoretical since I don't know a valid source of the im.close call but maybe it still helps. 

"pidgin -d" Snippet (I closed Pidgin a few seconds after Step 3, so no missing or extra debug entries):
(06:46:19) slack: RTM 1: {"type":"im_close","user":"U96QW9BFY","channel":"D95A1LBT2","event_ts":"1519710379.000152"}
(06:46:19) slack: RTM: {"id":2,"type":"presence_sub","ids":["USLACKBOT","U95ULHHLL"]}
(06:46:24) util: Writing file blist.xml to directory /home/d.bitterlich/.purple
(06:46:24) util: Writing file /home/d.bitterlich/.purple/blist.xml
(06:46:28) websocket: message 81 len 63
(06:46:28) slack: RTM 1: {"type":"user_typing","channel":"D95A1LBT2","user":"U96QW9BFY"}
(06:46:28) slack: Unhandled typing: U96QW9BFY@D95A1LBT2
(06:46:29) websocket: message 81 len 142
(06:46:29) slack: RTM 1: {"type":"message","channel":"D95A1LBT2","user":"U96QW9BFY","text":"foo","ts":"1519710389.000053","source_team":"T95S7P0AF","team":"T95S7P0AF"}
dns[31007]: nobody needs me... =(
(06:46:39) docklet: The button is 3
(06:46:39) account: Disconnecting account User1@slack.com (0x556f5de70ec0)


P.S. I think the behavior with everyone showing in the im.list is a result of the missing ability to remove entries from the im.list. If you close a channel with the im.close method it will still apear in the im.list. This is a problem of the Slack API.


P.P.S

Mentioned methods:
https://api.slack.com/methods/im.open
https://api.slack.com/methods/im.close
https://api.slack.com/methods/im.list

**Comment by dylex** [comment] 2018-03-02 00:35
Okay, that's a fair theory.  I've removed the im_close handling that forgets the id, in case slack does keep using it.  My one worry with this is it means may try to send a message on a closed im.

Do we think there's a chance that slack also sends messages on im channels without first sending an im.open?  In that case, maybe it would be better to catch this case and try to look up channel info whenever we get a message on an unknown channel.

**Comment by Itsmedenise** [comment] 2018-03-02 06:19
I tested a little bit more. When communicating between browser and pidgin there seem to be no im.* events involved. 
That means if you use the "+" icon next to "Direct messages" to open a new direct message channel no im.open will be recived in pidgin. On the other side if you close that channel in the browser no im.close will be recived.

An other thing to remember is that the im.list never forgets anyone you ever contacted from pidgin to browser (which triggers im.open).They will be on that list forever, therefore you will always be able to recive messages from them, as long as you don't recive an im.close in the current session. If you recived im.close and restart pidgin you can recive messages again because the channel is on the im.list and will be initialized on startup.

Now to people whe never interacted before, they are not on the im.list which means no initialization on startup and we don't recive an im.open when they write us from the browser, as a result pidgin doesn't handle the message.

Given all those behaviors I think the best solution would be to check if a channel is open when reciving a message event and open a channel if it is unknown to pidgin. The worst case is we recive a already open response on the im.open call because slack has it open but for some stupid reason it isn't initialized in pidgin which is required anyway.

Still untested:
Behavior when the other user is using the slack app or something that uses the slack api itself (bots or even pidgin)

**Comment by dylex** [comment] 2018-05-22 21:29
I finally got around to adding a hook so if we get a message on a channel id that we don't recognize, we do a conversations.info to look it up. This may help with this problem, but I've had a hard time reproducing it to be sure. (I think I did see it myself on one occasion but didn't have debugging at the time.)

**Comment by dylex** [comment] 2018-06-08 14:02
Though #73 gave me another idea that somehow it's the user we don't know about, not the IM, which would be strange since slack sends all the users at start, but could be worth adding a similar fallback when we don't know the user... I'll try that.

**Comment by kendrak24** [comment] 2018-06-11 15:32
I reproduced this. When receiving an IM from someone not yet on your buddy list, it seems like the channel is unknown:

> (16:54:19) slack: RTM 1: {"type":"message","channel":"DB12TP36J","user":"U36AT45BG","text":"Text message from user not on buddy list","ts":"1528728859.000688","source_team":"T3BGXUSR0","team":"T3BGXUSR0"}
(16:54:19) slack: api call: https://company.slack.com/api/conversations.info?token=xxx&channel=DB12TP36J
(16:54:19) util: requesting to fetch a URL
.... dns lookup and cert stuff ....
(16:54:19) slack: api response: {"ok":true,"channel":{"id":"DB12TP36J","created":1528728848,"is_im":true,"is_org_shared":false,"user":"U36AT45BG","last_read":"0000000000.000000","latest":{"type":"message","user":"U36AT45BG","text":"Text message from user not on buddy list","ts":"1528728859.000688"},"unread_count":1,"unread_count_display":1,"is_open":false,"priority":0}}
(16:54:19) slack: Message to unknown channel DB12TP36J

**Comment by dylex** [comment] 2018-06-11 15:35
That's quite useful. What revision was this with?

**Comment by kendrak24** [comment] 2018-06-11 15:35
Latest git.

**Comment by dylex** [comment] 2018-06-11 15:38
And you don't see a `users.info` call after the conversation response and before the unknown channel message?

**Comment by kendrak24** [comment] 2018-06-11 15:39
No.

**Comment by dylex** [comment] 2018-06-11 15:46
I just noticed that `is_open` is false. Why is slack sending a message on a closed channel? I guess the problem wasn't just missing the `im.open` but that slack doesn't even consider the channel open, but still sends messages on it. Let me see how I can deal with this.

**Comment by dylex** [comment] 2018-06-11 15:52
Yeah, I had assumed that meant just that we weren't getting the `im.open` event, but that it was being implicitly opened by the message.  Clearly something is opening the channel at some point, or we'd never get any messages on it.

**Comment by Itsmedenise** [comment] 2018-06-11 16:06
As far as my testing went the web client never opens a channel for DM's they don't seem to care about channels at all for dm's, as the state doesn't apply to the "friendlist" either. There seem to be something else that actually controls which contacts are shown in the "friendlist" but I haven't figured out what it is.

**Comment by kendrak24** [comment] 2018-06-11 17:05
I can probably reproduce this again. Let me know if/when the fix is complete.

**Comment by dylex** [comment] 2018-06-11 17:34
I'm hoping that last commit should fix it -- or at least produce some additional information. If it's easy enough to reproduce, that would be helpful. Thanks.

**Comment by kendrak24** [comment] 2018-06-12 10:22
Just tested and it seems to work now.

**Comment by dylex** [comment] 2018-06-12 19:52
Cool. Thanks all for the help.

**Closed by dylex** 2018-06-12 19:52 UTC
